name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - uses: docker/login-action@v1.10.0
    - name: Login to Dockerhub
    - with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag lomztein/moduthulhu:latest

    - name: Push Docker image
      run: docker push lomztein/moduthulhu:latest
